package by.bsuir.reguisites.model;

public enum SubjectEventType {
    CREATED_STATE_REGISTRATION,
    UPDATED_STATE_REGISTRATION,
    SUPERVISOR_UPDATE,
    LOCATION_UPDATE,
    LIQUIDATION,
    OPENED_BANKRUPTCY,
    LAUNCHED_BANKRUPTCY,
    BANKRUPTCY_LIQUIDATION,
    LIQUIDATION_FINISHED,
    EXCLUSION
}
