package by.bsuir.core.entity;

import by.bsuir.core.sequence.model.AutoGeneratedId;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

@Data
@Document(collection = "tests")
public class Test {

    @Id
    @AutoGeneratedId
    @Field(value = "_id")
    private Long id;

    @Field(value = "name")
    private String name;

    @Field(value = "number")
    private Integer number;
}
